name: chat_app
description: "A new Flutter project."
publish_to: 'none' # Prevents package publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cloud_firestore: ^6.0.3
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  modal_progress_hud_nsn: ^0.5.1

dev_dependencies:

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
